#!/bin/env python
# -*- coding: utf-8 -*-

def build(bld):
	sources = [
		'main.cpp',
		'bike.cpp',
		'box2d_util.cpp',
	]

	obj = bld.program(
		source=sources,
		target='hilastomania',
		use=['Box2D_inc', 'Box2D', 'ymse'],
	)
